### ISSUE TITLE
make compile is missing

### ISSUE THREAD

**Issue by szabgab** [r-lib/yaml#125]
The readme file indicates that there is a target called `compile` in the `Makefile`, but I could not find one.

I tried the following:

```
git clone git@github.com:vubiostat/r-yaml.git
docker run -it --name r-yaml --workdir /opt -v$(pwd):/opt r-base:4.2.3 bash
make compile
```

and I received

```
make: *** No rule to make target 'compile'.  Stop.
```

**Comment by spgarbet** [comment]
Use 

`make yaml_2.3.7.tar.gz`

That builds the tar ball. Then install it with

`RMD CMD install yaml_2.3.7.tar.gz`

**Comment by spgarbet** [comment]
I'll take that out of the README.md on the next release.
